#!/usr/bin/env sh

set -euf pipefail

cd ~/.local/share/thoughts

# get an editor so we can type our thought.
# generate a random temp filename to avoid collisions.
# who knows what's in there!
rand=$(date | cksum | tr -d ' ')
"${EDITOR:-vi}" "$rand".txt
if [ ! -f "$rand".txt ]; then
    echo "you don't always have to share your thoughts :)"
    exit 0
fi
# If this thought doesn't have a trailing newline, add one
tail -c 1 < "$rand".txt | read -r _ || echo >> "$rand".txt

# replace all newlines with <br>
# since we know EOF is a newline, remove the last four characters
sed 's/$/<br>/' "$rand".txt > temp.txt
mv temp.txt "$rand".txt
thought=$(sed '$ s/.\{4\}$//' "$rand".txt)
rm "$rand".txt

now=$(date +"%I:%M %p | %Y-%m-%d")
dateHash=$(date | cksum | tr -d ' ')
blob="<p><a class=\"thought\" id=$dateHash href=#$dateHash>
$now</a><br>
$thought
</p>
"
git pull
echo "$blob" | cat - .rawthoughts.html > "$dateHash".html && mv "$dateHash".html .rawthoughts.html
cat .head.html .rawthoughts.html | cat - .foot.html > thoughts.html
git add .
git commit -m "add thoughts"
git push
echo "your thoughts have been shared :)"
