#!/bin/bash

set -eou pipefail

cd ~/.local/share/thoughts

now=$(date +"%D %r")
rand=$(echo $now | sha256sum | cut -c -16)
command vim $rand.txt
thought=$(sed -z 's/\n/<br>\n/g' $rand.txt)
thought=${thought%????}
rm $rand.txt

now=$(date +"%D %r")
dateHash=$(echo $now | sha256sum | cut -c -16)
blob="<p><a id="$dateHash" href="#$dateHash"><span style="font-weight:bold">
$now
</span></a><br>
$thought
</p>
"
git pull
echo "$blob" | cat - .rawthoughts.html > $dateHash.html && mv $dateHash.html .rawthoughts.html
cat .head.html .rawthoughts.html | cat - .foot.html > thoughts.html
git add .
git commit -m "i had a thought"
git push
echo "thought recorded :)"
